"""Report builder: deterministic numbers + LLM narrative."""

from __future__ import annotations

from functools import lru_cache

from pydantic_ai import Agent

from invoice_agent.models.schemas import (
    AggregationResult,
    FinalReport,
    ProcessedInvoice,
    ReportNarrative,
)
from invoice_agent.settings import get_settings

REPORT_SYSTEM_PROMPT = (
    "You are an expense report assistant for a finance team. "
    "Given a list of processing observations, generate concise, professional "
    "Issues & Assumptions bullet points for an expense report. "
    "Be factual. Do not invent issues. Use one sentence per bullet."
)


@lru_cache(maxsize=1)
def _get_report_agent() -> Agent[None, ReportNarrative]:
    """Create and cache the report agent."""
    return Agent(
        get_settings().report_model,
        output_type=ReportNarrative,
        system_prompt=REPORT_SYSTEM_PROMPT,
        defer_model_check=True,
    )


def _collect_observations(
    invoices: list[ProcessedInvoice],
    aggregation: AggregationResult,
) -> str:
    """Build the factual observation string passed to the report LLM."""
    lines: list[str] = []

    currencies = {
        inv.currency for inv in invoices if inv.currency and not inv.extraction_failed
    }
    if len(currencies) > 1:
        lines.append(
            f"Mixed currencies detected: {', '.join(sorted(currencies))}. "
            "Totals were summed without FX conversion."
        )

    if aggregation.failed_count > 0:
        lines.append(
            f"{aggregation.failed_count} invoice(s) could not be extracted "
            "and were excluded from totals."
        )

    for inv in invoices:
        if not inv.invoice_date and not inv.extraction_failed:
            lines.append(f"{inv.source_file}: invoice date could not be parsed.")
        for warning in inv.validation_warnings:
            lines.append(f"{inv.source_file}: {warning}")

    # Always include the date ambiguity assumption
    lines.append(
        "Date format assumption: MM/DD/YYYY is assumed over DD/MM/YYYY "
        "for slash-separated dates."
    )

    return "\n".join(lines) if lines else "No issues detected."


async def build_report(
    invoices: list[ProcessedInvoice],
    aggregation: AggregationResult,
) -> FinalReport:
    """Build the final report.

    Numbers come from AggregationResult (deterministic).
    Issues & Assumptions narrative is generated by LLM from factual
    observations.
    """
    observations = _collect_observations(invoices, aggregation)
    narrative_result = await _get_report_agent().run(f"Observations:\n{observations}")

    return FinalReport(
        total_spend=str(aggregation.total_spend),
        spend_by_category={k: str(v) for k, v in aggregation.spend_by_category.items()},
        invoices=[
            {
                "source_file": inv.source_file,
                "vendor": inv.vendor,
                "invoice_date": inv.invoice_date,
                "invoice_number": inv.invoice_number,
                "total": str(inv.total) if inv.total is not None else None,
                "currency": inv.currency,
                "category": inv.category,
                "confidence": inv.confidence,
                "notes": inv.notes,
            }
            for inv in invoices
        ],
        issues_and_assumptions=narrative_result.output.issues_and_assumptions,
    )
